apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  labels:
    type: nfs
    storage: nfs
provisioner: example.com/nfs
volumeBindingMode: Immediate
parameters:
  archiveOnDelete: "false"

#kubectl patch storageclass managed-nfs-storage -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'