apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-claim
  labels:
    type: nfs
    storage: nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 10Gi
